modes:
    stickiness:
        output_file: "stickiness"
    overlaps:
        output_file: "overlaps"
    uncaught:
        output_file: "uncaught"
    host_aggregate:
        output_file: "host_aggregate"
input_files:
    regex_file: "regeces"
    alerts_file: "u_alerts_to_task.filtered.csv"
